CREATE DATABASE Intranet;
USE Intranet;

CREATE TABLE Aplicaciones(
idApp INTEGER AUTO_INCREMENT NOT NULL,
nombre VARCHAR(30),
link VARCHAR(500),
tipo VARCHAR(30),
idImagen INTEGER,

PRIMARY KEY(idApp)
);

CREATE TABLE Adjunto(
idAdj INTEGER AUTO_INCREMENT NOT NULL,
tipoArchivo VARCHAR(255) NULL,
nombreArchivo VARCHAR(255) NULL,
adjuntoArchivo LONGTEXT NULL,

PRIMARY KEY(idAdj)
);

CREATE TABLE Catalogo(
idCat INTEGER AUTO_INCREMENT NOT NULL,
nombre VARCHAR(255) NULL,
idBib INTEGER,
idPdf INTEGER,

PRIMARY KEY(idCat)
);

CREATE TABLE Biblioteca(
idBib INTEGER AUTO_INCREMENT NOT NULL,
nombre VARCHAR(255) NULL,

PRIMARY KEY(idBib)
);

CREATE TABLE Users(
idUser INTEGER AUTO_INCREMENT NOT NULL,
userName VARCHAR(255) NULL,
userPass VARCHAR(255) NULL,
idRol INTEGER,

PRIMARY KEY(idUser)
);

CREATE TABLE Rol(
idRol INTEGER AUTO_INCREMENT NOT NULL,
descripcion VARCHAR(30) NULL,

PRIMARY KEY(idRol)
);

CREATE TABLE Eventos(
idEvent INTEGER AUTO_INCREMENT NOT NULL,
title VARCHAR(50) NULL,
start DATETIME,
end DATETIME,
PRIMARY KEY(idEvent)
);

CREATE TABLE Enterates(
idEnt INTEGER AUTO_INCREMENT NOT NULL,
titulo VARCHAR(50) NULL,
fecha DATETIME,
idAdj INTEGER,
PRIMARY KEY(idEnt)
);
